import { Box } from "@mui/material";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomePage from './home/index';

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{m:10,pt:1}}>
      <HomePage />
      </Box>
    </div>
  );
}
